services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - todo-network
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "dBq7qq09Z3B4ofAN4UrN" -Q "SELECT 1" || exit 1
      interval: 30s    # 增加間隔時間
      timeout: 10s     # 增加超時時間
      retries: 10      # 增加重試次數
      start_period: 60s  # 新增啟動緩衝期

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;    
      - ASPNETCORE_URLS=http://+:80
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryInMinutes=${JWT_EXPIRY_MINUTES}
      - AllowedOrigins__0=http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - todo-network
    restart: always

volumes:
  sqlserver-data:
    name: todo-sqlserver-data

networks:
  todo-network:
    name: todo-network